version: "{build}"
image: Visual Studio 2017

branches:
  only:
  - master
  - appveyor
  - hunter
configuration:
  - Release
environment:
  HUNTER_CACHE_TOKEN:
    secure: agYfiC1OKfHnGOJQolOBorIRovVTgDW3TJ8JOb2+0XZiAnNwbrtPegxaaFM8/VWu
  matrix:
    - ARCH: amd64
      CONFIGURATION: Debug
    - ARCH: x86
    - ARCH: amd64

install:
  # Python 3
  - set PATH_ORIG=%PATH%
  - set PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%PATH_ORIG%
  - pip install requests

before_build:
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd" -arch=%ARCH%
  - if not exist build mkdir build
  - cd build
  - cmake -GNinja .. -DCMAKE_INSTALL_PREFIX=../dist -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DHUNTER_CONFIGURATION_TYPES=%CONFIGURATION%

build_script:
  - cmake --build . --target install

test_script:
  - if %CONFIGURATION%==Release C:\projects\ethash\build\test\ethash-test.exe

artifacts:
  - path: dist
    name: dist
