image: Visual Studio 2017
version: "{build}"
branches:
  only:
  - master
configuration:
  - Release

install: |
  git submodule update --init

before_build: |
  if not exist build mkdir build
  cd build
  cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: c:/projects/ethash/build/ethash.sln
  parallel: true
  verbosity: minimal
